"""empty message

Revision ID: 450113e7d830
Revises: 20ce9577e79b
Create Date: 2022-04-08 14:02:07.427210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '450113e7d830'
down_revision = '20ce9577e79b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
